server:
  port: 8900
  servlet:
    context-path: /


pring:
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl

spring:
  datasource:
    url: jdbc:mysql://119.45.17.181:3306/zichan?userUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    username: root
    password: wuzhiqian
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
  mapper-locations: classpath:com/gongxiao/zichan/mapper/*.xml
  type-aliases-package: com.gongxiao.zichan.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  returnPageInfo: check

logging:
  level:
    com.gongxiao.zichan.mapper: debug



#自定义文件上传路径
web:
  upload-path: /Zgy/imgUpload/
